language: python
dist: xenial
python:
  - '3.4'
  - '3.5'
  - '3.6'
  - '3.7'
install:
  - pip install -r requirements.txt
  - pip install --no-deps -e .
script:
  - pytest
deploy:
  provider: pypi
  user: joshbode
  password:
    secure: HvH2EnsbkIe9pJ9wpDn8i7UpZ65lREBxRMfqoNHgN7RIgCTHkQDgQWobJsXMewT7NBVe6trdi5PoAzWjPH+ZjrSlrGLxoK2OhfF5NqHGuKCS0V2OFO9SriaD2++5KY1yX1KnlSickZ6873hB/QZdwLTFbSLRqo8zaKX0uYhclMmSZ8P5MbR0yXPFK9cVoM+2WOYKouqXEv5H3OYLMpvmmlb3Lqcg2TVE+A2NtgQxtpggmlOgb5+4K1HOgZkWhaKVSFUqjs3fHZZ9yjvRb3bpSKs4VUk4V3YBhGYvCFakz6vDkVdGdEGO8dGo9uXI2GQfmKhuJfqWbAXl3JG115uSuuU3WPhv/Y7qvJD1mIqWzWrlUi2tMIkU6OEXJVkcCCuL3Fd53lstt0kpEfhSInnWahokBEfVGA8/1echoVIcoP0Nkmn9osChUISdXmFTBCAjQRMH45uWE8ujvcDO+fRWeIsvJyNXs9FuagcxC+tabfLeCrVr12UGLtUqoOq0RatAE4NTiAbSTElLDNuJ1XPWMcCZkaPfYceZ2lAVKzkoonX2NWlz1UfOsxCXOIIkEDibJnPXjq6TQooQJgoFqAv8or8pgmeUHArp6GcX7iOJ/IfeUhGxPz+G1JQjFvcdcLlaGU50+R1dHaOESQTvx8znA6NkCe2eoIoOJu944m4zXYE=
  on:
    tags: true
  distributions: sdist bdist_wheel
